import * as esbuild from 'esbuild';
import * as crypto from 'node:crypto';
import * as fs from 'node:fs';
import * as path from 'node:path';

const args = process.argv.slice(2);
const has = (f) => args.includes(f);
const watch = has('--watch');

// ---------------------------------------------------------------------------
// out/extension.js — the ONE shipped artifact and the ONLY .js in the .vsix.
// Algorithms (@noble/hashes, pure-JS) are bundled IN, so there is no separate
// algorithms.js and no host-crypto dependency. QA certifies THIS exact file.
//
// `vscode` is a STANDARD external (the editor host provides it at runtime —
// the proven, normal way every VSCode extension is built). The QA harness
// loads this same file under plain Node via a process-level 'vscode' stub
// preload (qa/vscode-stub.cjs, added by the npm script's `node -r` flag);
// the committed QA package is never altered.
// ---------------------------------------------------------------------------
// `vscode` is a STANDARD external (exactly how every VSCode extension — and
// our previously-working packages — are built; the editor's host provides it
// at runtime). No custom shim: the shim was the only structural difference
// vs the working builds and it broke editor activation. The QA harness loads
// this same file under plain Node via a process-level 'vscode' stub preload
// (qa/vscode-stub.cjs, invoked by the npm script) — the committed QA package
// itself is never altered.
async function buildExtension(min = true) {
  await esbuild.build({
    entryPoints: ['src/extension.ts'],
    bundle: true,
    outfile: 'out/extension.js',
    platform: 'node',
    target: 'node22',
    format: 'cjs',
    external: ['vscode'],
    minify: min,
    sourcemap: !min,
    logLevel: 'info',
  });
  console.log('esbuild: single bundled extension written to out/extension.js');
}

// ---------------------------------------------------------------------------
// qa/.staging-qa/qa.pkg.mjs — the single all-inclusive QA package.
//
// INDEPENDENCE: the control declares its OWN expected algorithm set and
// inputs from audited committed data (baseline/algorithms.json,
// baseline/test-strings.json). It does NOT read src/ or out/algorithms.js —
// so it never needs the code-under-test to be built first, and it can never
// silently reshape itself to whatever the code happens to expose. Expected
// digests come from the Node crypto oracle. Staging only; promote+commit are
// deliberate steps.
// ---------------------------------------------------------------------------
async function buildQaPackage() {
  const repoRoot = process.cwd();

  const { algorithms: ALGORITHMS } = JSON.parse(
    fs.readFileSync(path.join(repoRoot, 'baseline', 'algorithms.json'), 'utf8'),
  );
  const testStrings = JSON.parse(
    fs.readFileSync(path.join(repoRoot, 'baseline', 'test-strings.json'), 'utf8'),
  );

  const available = new Set(crypto.getHashes());
  const missing = ALGORITHMS.filter((a) => !available.has(a.cryptoName));
  if (missing.length) {
    console.error(
      'FATAL  algorithms unavailable in this Node/OpenSSL build: ' +
      missing.map((a) => a.cryptoName).join(', '),
    );
    process.exit(1);
  }

  // Oracle = raw Node crypto, independent of the code under test. The KAT
  // vectors validated at QA run time anchor that this oracle is correct.
  const hashes = {};
  for (const s of testStrings.strings) {
    const perAlgo = {};
    for (const algo of ALGORITHMS) {
      const raw = crypto.createHash(algo.cryptoName).update(s.value, 'utf8').digest();
      perAlgo[algo.cryptoName] = {
        hex: raw.toString('hex'),
        base64: raw.toString('base64'),
      };
    }
    hashes[s.id] = perAlgo;
  }
  const baseline = {
    schema: 1,
    generatedBy: 'esbuild.mjs --qa (oracle: Node crypto)',
    algorithms: ALGORITHMS.map((a) => ({
      id: a.id,
      cryptoName: a.cryptoName,
      label: a.label,
      legacy: !!a.legacy,
    })),
    strings: testStrings.strings,
    hashes,
  };

  const dataModule =
    '// GENERATED by `npm run gen:qa` — do not edit; gitignored.\n' +
    `export const BASELINE = ${JSON.stringify(baseline)};\n` +
    `export const TEST_STRINGS = ${JSON.stringify(testStrings)};\n`;
  fs.writeFileSync(path.join(repoRoot, 'qa', 'embedded-data.mjs'), dataModule);

  const stagingDir = path.join(repoRoot, 'qa', '.staging-qa');
  fs.mkdirSync(stagingDir, { recursive: true });
  const outfile = path.join(stagingDir, 'qa.pkg.mjs');

  await esbuild.build({
    entryPoints: [path.join(repoRoot, 'qa', 'qa.mjs')],
    bundle: true,
    outfile,
    platform: 'node',
    target: 'node22',
    format: 'esm',
    minify: true,
    sourcemap: false,
    treeShaking: true,
    logLevel: 'info',
  });

  const n = testStrings.strings.length * ALGORITHMS.length * 2;
  console.log(
    `esbuild: QA package (json+js) written to ${outfile}\n` +
    `  embedded ${testStrings.strings.length} strings x ${ALGORITHMS.length} ` +
    `algorithms x {hex,base64} = ${n} values + the self-verifying test harness\n\n` +
    'STAGING candidate — NOT used by QA until promoted and committed:\n' +
    '  1. Review/revalidate it.\n' +
    '  2. npm run qa:promote\n' +
    '  3. git add qa-dist && git commit -m "update QA package"',
  );
}

if (has('--qa')) {
  await buildQaPackage();
} else if (watch) {
  // Dev: unminified single bundle, rebuild on change.
  const ctx = await esbuild.context({
    entryPoints: ['src/extension.ts'],
    bundle: true,
    outfile: 'out/extension.js',
    platform: 'node',
    target: 'node22',
    format: 'cjs',
    external: ['vscode'],
    minify: false,
    sourcemap: true,
    logLevel: 'info',
  });
  await ctx.watch();
  console.log('esbuild: watching (single bundled extension)...');
} else {
  // Default and --extension: the one shipped, minified bundle.
  await buildExtension(true);
}
