import * as esbuild from 'esbuild';
import * as crypto from 'crypto';
import { createRequire } from 'module';
import * as fs from 'fs';
import * as path from 'path';

const watch = process.argv.includes('--watch');
const test = process.argv.includes('--test');
const qa = process.argv.includes('--qa');

if (test) {
  // Bundle of the production hash/transcoder logic = the CODE UNDER TEST.
  // Freshly built each QA run so the frozen harness validates the CURRENT
  // extension code. Gitignored, never shipped in the .vsix.
  await esbuild.build({
    entryPoints: ['src/algorithms.ts'],
    bundle: true,
    outfile: 'qa/algorithms.cjs',
    platform: 'node',
    target: 'node16',
    format: 'cjs',
    minify: false,
    sourcemap: false,
    logLevel: 'info',
  });
  console.log('esbuild: code-under-test bundle written to qa/algorithms.cjs');
} else if (qa) {
  // Build the SINGLE QA PACKAGE: the JSON baseline data + the JS test harness
  // bundled together into ONE file. Written to gitignored staging only; it is
  // never auto-promoted and never auto-run. Promote + revalidate + commit are
  // deliberate steps (see qa/promote-qa.mjs, qa/run-qa.mjs).
  const require = createRequire(import.meta.url);
  const repoRoot = process.cwd();
  const algoBundle = path.join(repoRoot, 'qa', 'algorithms.cjs');
  if (!fs.existsSync(algoBundle)) {
    console.error('FATAL  qa/algorithms.cjs missing — run `npm run build:test` first.');
    process.exit(1);
  }
  const { ALGORITHMS } = require(algoBundle);

  const testStrings = JSON.parse(
    fs.readFileSync(path.join(repoRoot, 'baseline', 'test-strings.json'), 'utf8'),
  );

  const available = new Set(crypto.getHashes());
  const missing = ALGORITHMS.filter((a) => !available.has(a.cryptoName));
  if (missing.length) {
    console.error(
      'FATAL  algorithms unavailable in this Node/OpenSSL build: ' +
        missing.map((a) => a.cryptoName).join(', '),
    );
    process.exit(1);
  }

  // Oracle (raw Node crypto, independent of the code under test) computes
  // every expected digest. The KAT vectors validated at QA run time anchor
  // that this oracle is itself correct.
  const hashes = {};
  for (const s of testStrings.strings) {
    const perAlgo = {};
    for (const algo of ALGORITHMS) {
      const raw = crypto.createHash(algo.cryptoName).update(s.value, 'utf8').digest();
      perAlgo[algo.cryptoName] = {
        hex: raw.toString('hex'),
        base64: raw.toString('base64'),
      };
    }
    hashes[s.id] = perAlgo;
  }
  const baseline = {
    schema: 1,
    generatedBy: 'esbuild.mjs --qa (oracle: Node crypto)',
    algorithms: ALGORITHMS.map((a) => ({
      id: a.id,
      cryptoName: a.cryptoName,
      label: a.label,
      legacy: !!a.legacy,
    })),
    strings: testStrings.strings,
    hashes,
  };

  // Write the dataset as a module that qa.mjs imports; esbuild then inlines
  // it, so the JSON data and JS test logic become ONE all-inclusive file.
  // This generated module is gitignored — the committed truth is the bundle.
  const dataModule =
    '// GENERATED by `npm run gen:qa` — do not edit; gitignored.\n' +
    `export const BASELINE = ${JSON.stringify(baseline)};\n` +
    `export const TEST_STRINGS = ${JSON.stringify(testStrings)};\n`;
  fs.writeFileSync(path.join(repoRoot, 'qa', 'embedded-data.mjs'), dataModule);

  const stagingDir = path.join(repoRoot, 'qa', '.staging-qa');
  fs.mkdirSync(stagingDir, { recursive: true });
  const outfile = path.join(stagingDir, 'qa.pkg.mjs');

  await esbuild.build({
    entryPoints: [path.join(repoRoot, 'qa', 'qa.mjs')],
    bundle: true,
    outfile,
    platform: 'node',
    target: 'node18',
    format: 'esm',
    minify: false,
    sourcemap: false,
    logLevel: 'info',
  });

  const n = testStrings.strings.length * ALGORITHMS.length * 2;
  console.log(
    `esbuild: QA package (json+js) written to ${outfile}\n` +
      `  embedded ${testStrings.strings.length} strings x ${ALGORITHMS.length} ` +
      `algorithms x {hex,base64} = ${n} values + the test harness\n\n` +
      'This is a STAGING candidate. It is NOT used by QA until promoted and ' +
      'committed. Next:\n' +
      '  1. Review/revalidate the candidate.\n' +
      '  2. npm run qa:promote          (copies it to qa-dist/qa.pkg.mjs)\n' +
      '  3. git add qa-dist && git commit -m "update QA package"\n' +
      'QA refuses to run an uncommitted package.',
  );
} else {
  const production = !watch;

  /** @type {import('esbuild').BuildOptions} */
  const options = {
    entryPoints: ['src/extension.ts'],
    bundle: true,
    outfile: 'out/extension.js',
    platform: 'node',
    target: 'node16',
    format: 'cjs',
    // Host-provided at runtime; never bundle it. Node built-ins (crypto, etc.)
    // are external on the 'node' platform automatically.
    external: ['vscode'],
    minify: production,
    sourcemap: !production,
    logLevel: 'info',
  };

  if (watch) {
    const ctx = await esbuild.context(options);
    await ctx.watch();
    console.log('esbuild: watching for changes...');
  } else {
    await esbuild.build(options);
    console.log('esbuild: production bundle written to out/extension.js');
  }
}
