/**
 * Standalone QA harness — the mandatory gate before `vsce package`.
 *
 * Trust chain (no circularity):
 *   1. KAT      — published vectors are external ground truth.
 *   2. Oracle   — Node `crypto` reproduces the KAT → oracle is trustworthy.
 *   3. Baseline — qa/baseline.json is a FROZEN, human-reviewed dataset
 *                 generated by that oracle (qa/gen-baseline.mjs). Each QA run
 *                 re-derives it with the oracle and asserts it is unchanged,
 *                 so a tampered/stale baseline or a forked OpenSSL aborts.
 *   4. Code     — the PRODUCTION computeDigest()/TRANSCODERS (bundled to
 *                 qa/algorithms.cjs) are asserted equal to the baseline.
 *
 * The baseline is the permanent comparison target — QA never silently
 * regenerates it. Every assertion prints to stdout (what, expected, got,
 * diff on mismatch). Non-zero exit on any failure.
 *
 * Env: QA_SEED=<int> transcoder-subset seed; QA_FULL=1 full corpus;
 *      QA_QUIET=1 (or --quiet) collapse PASS lines (FAILs always printed).
 */
import * as crypto from 'crypto';
import { createRequire } from 'module';
import { execFileSync } from 'child_process';
import { fileURLToPath } from 'url';
import * as fs from 'fs';
import * as path from 'path';
import { KAT } from './vectors.mjs';
import { generateCorpus, makeRng } from './corpus.mjs';

const require = createRequire(import.meta.url);
const here = path.dirname(fileURLToPath(import.meta.url));

let prod;
try {
  prod = require(path.join(here, 'algorithms.cjs'));
} catch (e) {
  console.error(
    'FATAL  qa/algorithms.cjs missing — run `npm run build:test` first.\n' +
      String(e),
  );
  process.exit(1);
}
const { ALGORITHMS, TRANSCODERS, computeDigest } = prod;

// ---------------------------------------------------------------------------
// Baseline is read ONLY from the COMMITTED /baseline folder (git HEAD).
// Uncommitted / staged / working-tree / untracked baseline data is NEVER
// used to QA against — explicit project rule.
// ---------------------------------------------------------------------------
let repoRoot;
try {
  repoRoot = execFileSync('git', ['rev-parse', '--show-toplevel'], {
    encoding: 'utf8',
    stdio: ['pipe', 'pipe', 'pipe'],
  }).trim();
} catch {
  console.error(
    'FATAL  Not a git repository (or git unavailable). QA only trusts ' +
      'COMMITTED baseline data and cannot verify commit state here. Aborting.',
  );
  process.exit(1);
}

/**
 * Content of `relPath` as committed at HEAD, or null if not committed.
 * `relPath` is a fixed in-repo path passed as an argv element (no shell).
 */
function gitCommitted(relPath) {
  try {
    return execFileSync('git', ['show', `HEAD:${relPath}`], {
      cwd: repoRoot,
      encoding: 'utf8',
      stdio: ['pipe', 'pipe', 'pipe'],
      maxBuffer: 32 * 1024 * 1024,
    });
  } catch {
    return null;
  }
}

function loadCommittedJson(relPath) {
  const committed = gitCommitted(relPath);
  if (committed === null) {
    console.error(
      `FATAL  ${relPath} is not committed at HEAD. QA refuses to run ` +
        'against an uncommitted baseline. Generate → review → ' +
        '`npm run baseline:promote` → `git add baseline && git commit`, ' +
        'then re-run QA.',
    );
    process.exit(1);
  }
  // Inform (do not fail) if the working tree differs — QA uses committed bytes.
  const onDisk = path.join(repoRoot, relPath);
  if (fs.existsSync(onDisk) && fs.readFileSync(onDisk, 'utf8') !== committed) {
    console.log(
      `NOTE  ${relPath} has uncommitted working-tree changes; QA is using ` +
        'the COMMITTED version and ignoring those changes.',
    );
  }
  try {
    return JSON.parse(committed);
  } catch (e) {
    console.error(`FATAL  committed ${relPath} is not valid JSON: ${e}`);
    process.exit(1);
  }
}

const baseline = loadCommittedJson('baseline/baseline.json');
const canonicalStrings = loadCommittedJson('baseline/test-strings.json').strings;

const QUIET = process.env.QA_QUIET === '1' || process.argv.includes('--quiet');
const FULL = process.env.QA_FULL === '1';
const SEED = (process.env.QA_SEED && Number(process.env.QA_SEED)) || 0x5eed;

let passCount = 0;
let failCount = 0;
const sectionStats = [];

// ---------------------------------------------------------------------------
// Rendering helpers
// ---------------------------------------------------------------------------

function fingerprint(s) {
  return crypto.createHash('sha256').update(s, 'utf8').digest('hex').slice(0, 8);
}
function reprInput(s) {
  if (s.length <= 60) return JSON.stringify(s);
  return (
    `${JSON.stringify(s.slice(0, 24))}…${JSON.stringify(s.slice(-12))}` +
    ` (len=${s.length}, sha256=${fingerprint(s)})`
  );
}
function shortVal(v) {
  v = String(v);
  if (v.length <= 96) return v;
  return `${v.slice(0, 72)}…${v.slice(-12)} (len=${v.length})`;
}
function diff(expected, got) {
  let lenNote;
  if (expected.length !== got.length) {
    lenNote = `lengths differ: expected ${expected.length}, got ${got.length}`;
  }
  const n = Math.min(expected.length, got.length);
  let i = 0;
  for (; i < n; i++) if (expected[i] !== got[i]) break;
  if (i === n && !lenNote) return 'identical (unexpected)';
  const at = i < n ? i : n;
  const parts = [];
  if (lenNote) parts.push(lenNote);
  if (i < n) {
    const eWin = expected.slice(Math.max(0, at - 8), at + 8);
    const gWin = got.slice(Math.max(0, at - 8), at + 8);
    parts.push(
      `first differs at index ${at}: ` +
        `expected ${JSON.stringify(expected[at])} vs got ${JSON.stringify(got[at])}`,
    );
    parts.push(`  expected …${eWin}…`);
    parts.push(`  got      …${gWin}…`);
    parts.push(`           ${' '.repeat(Math.min(8, at) + 1)}^`);
  }
  return parts.join('\n        ');
}
function pass(section, label, expected, got) {
  passCount++;
  if (!QUIET) {
    const tail =
      expected === undefined
        ? ''
        : `  expected=${shortVal(expected)}  got=${shortVal(got)}`;
    console.log(`PASS  ${section}  ${label}${tail}`);
  }
}
function fail(section, label, expected, got, extra) {
  failCount++;
  console.log(`FAIL  ${section}  ${label}`);
  if (expected !== undefined) {
    console.log(`        expected: ${shortVal(expected)}`);
    console.log(`        got:      ${shortVal(got)}`);
    console.log(`        diff:     ${diff(String(expected), String(got))}`);
  }
  if (extra) console.log(`        note:     ${extra}`);
}
function check(section, label, expected, got, extra) {
  const ok = expected === got;
  if (ok) pass(section, label, expected, got);
  else fail(section, label, expected, got, extra);
  return ok;
}
function expectThrow(section, label, fn) {
  let threw = false;
  let msg = '';
  try {
    fn();
  } catch (e) {
    threw = true;
    msg = e instanceof Error ? e.message : String(e);
  }
  if (threw) {
    passCount++;
    if (!QUIET) console.log(`PASS  ${section}  ${label}  (rejected: ${msg})`);
  } else {
    failCount++;
    console.log(`FAIL  ${section}  ${label}`);
    console.log('        note:     expected the decode to throw, but it did not');
  }
}
function banner(t) {
  console.log(`\n=== ${t} ===`);
}
function endSection(name) {
  sectionStats.push({ name, pass: passCount, fail: failCount });
}
function printSummaryAndExit() {
  banner('SUMMARY');
  let lp = 0;
  let lf = 0;
  for (const s of sectionStats) {
    console.log(
      `  ${s.name.padEnd(24)}  ${s.pass - lp} passed, ${s.fail - lf} failed`,
    );
    lp = s.pass;
    lf = s.fail;
  }
  console.log(
    `\n  TOTAL: ${passCount} passed, ${failCount} failed ` +
      `(seed=0x${SEED.toString(16)}, ${FULL ? 'FULL' : 'subset'})`,
  );
  console.log(
    failCount > 0
      ? '\nRESULT: FAIL — packaging must not proceed.'
      : '\nRESULT: PASS — safe to package.',
  );
  process.exit(failCount > 0 ? 1 : 0);
}

// ---------------------------------------------------------------------------
// 1. Validate the oracle against published KAT vectors
// ---------------------------------------------------------------------------

banner('1. Oracle validation (published KAT vectors)');
const availableHashes = new Set(crypto.getHashes());
let abort = false;
for (const v of KAT) {
  const label = `${v.cryptoName}(${JSON.stringify(v.input)})`;
  if (!availableHashes.has(v.cryptoName)) {
    fail('kat', label, v.expected, '<algorithm unavailable in this Node build>');
    abort = true;
    continue;
  }
  const oracle = crypto.createHash(v.cryptoName).update(v.input, 'utf8').digest('hex');
  if (!check('kat', label, v.expected, oracle)) abort = true;
}
endSection('oracle/KAT');
if (abort) {
  console.log(
    '\nFATAL  The oracle (Node crypto) does not reproduce the published ' +
      'vectors. Refusing to validate against an untrustworthy oracle.',
  );
  printSummaryAndExit();
}

// ---------------------------------------------------------------------------
// 2. Baseline integrity (frozen dataset is trustworthy in this environment)
// ---------------------------------------------------------------------------

banner('2. Baseline integrity (qa/baseline.json vs oracle + canonical strings)');

// 2a. Frozen strings must match the canonical test-strings.json exactly.
{
  const a = JSON.stringify(canonicalStrings);
  const b = JSON.stringify(baseline.strings);
  if (!check('baseline', 'strings == test-strings.json', a, b,
    'baseline is stale vs canonical strings — run `npm run gen:baseline`')) {
    abort = true;
  }
}

// 2b. Production algorithm registry must be exactly covered by the baseline.
{
  const reg = ALGORITHMS.map((a) => a.cryptoName).sort().join(',');
  const base = baseline.algorithms.map((a) => a.cryptoName).sort().join(',');
  if (!check('baseline', 'algorithms == production registry', reg, base,
    'extension algorithm set changed — regenerate the baseline')) {
    abort = true;
  }
}

// 2c. Re-derive every baseline digest with the oracle; must be unchanged.
for (const s of baseline.strings) {
  for (const algo of baseline.algorithms) {
    const cell = baseline.hashes[s.id]?.[algo.cryptoName];
    if (!cell) {
      fail('baseline', `${s.id}/${algo.cryptoName} present`, '<hex+base64>', '<missing>');
      abort = true;
      continue;
    }
    const raw = crypto.createHash(algo.cryptoName).update(s.value, 'utf8').digest();
    if (!check('baseline', `${s.id} ${algo.label} hex (oracle)`, raw.toString('hex'), cell.hex,
      'baseline hex differs from oracle — tampered or env drift')) abort = true;
    if (!check('baseline', `${s.id} ${algo.label} b64 (oracle)`, raw.toString('base64'), cell.base64,
      'baseline base64 differs from oracle — tampered or env drift')) abort = true;
  }
}
endSection('baseline integrity');
if (abort) {
  console.log(
    '\nFATAL  Baseline failed integrity. The frozen dataset is not ' +
      'trustworthy in this environment; aborting before testing the ' +
      'extension. Investigate, then `npm run gen:baseline` and review.',
  );
  printSummaryAndExit();
}

// ---------------------------------------------------------------------------
// 3. Extension output vs the FROZEN baseline  (the core requirement)
// ---------------------------------------------------------------------------

banner('3. Extension production output vs frozen baseline');
for (const s of baseline.strings) {
  for (const algo of baseline.algorithms) {
    const cell = baseline.hashes[s.id][algo.cryptoName];
    const inputRepr = `${s.id} (${reprInput(s.value)})`;
    check(
      'hash',
      `${algo.label} hex   ${inputRepr}`,
      cell.hex,
      computeDigest(algo.cryptoName, s.value, 'hex', false),
    );
    check(
      'hash',
      `${algo.label} b64   ${inputRepr}`,
      cell.base64,
      computeDigest(algo.cryptoName, s.value, 'base64', false),
    );
  }
}

// Encoding-path coverage not stored in the baseline: base64url + uppercase
// hex, checked against the oracle (the same trusted source the baseline used).
const spotAlgos = ['sha256', 'sha3-512', 'blake2b512', 'md5'];
for (const s of baseline.strings.slice(0, 3)) {
  for (const name of spotAlgos) {
    const raw = crypto.createHash(name).update(s.value, 'utf8').digest();
    check('hash', `${name} base64url  ${s.id}`,
      raw.toString('base64url'), computeDigest(name, s.value, 'base64url', false));
    check('hash', `${name} HEX-upper  ${s.id}`,
      raw.toString('hex').toUpperCase(), computeDigest(name, s.value, 'hex', true));
  }
}
endSection('extension vs baseline');

// ---------------------------------------------------------------------------
// 4. Transcoders / encoders / decoders
// ---------------------------------------------------------------------------

banner(
  `4. Transcoders (${FULL ? 'FULL corpus' : 'random subset'}, seed=0x${SEED.toString(16)})`,
);
const pairs = new Map();
for (const t of TRANSCODERS) {
  const p = pairs.get(t.label) || { label: t.label };
  p[t.direction] = t;
  pairs.set(t.label, p);
}
const encodeOracle = {
  Base64: (s) => Buffer.from(s, 'utf8').toString('base64'),
  Base64URL: (s) => Buffer.from(s, 'utf8').toString('base64url'),
  'URL (percent)': (s) => encodeURIComponent(s),
  Hex: (s) => Buffer.from(s, 'utf8').toString('hex'),
  'HTML Entities': (s) =>
    s.replace(/[&<>"']/g, (c) =>
      ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c])),
};

// Payloads: the frozen baseline strings (always tested) + corpus fuzz +
// real digest hex strings (good payloads).
const corpus = generateCorpus();
const hashPayloads = baseline.strings
  .slice(0, 4)
  .map((s) => baseline.hashes[s.id].sha256.hex);
const fuzzPool = [...corpus.map((c) => c.value), ...hashPayloads];

let fuzz;
if (FULL) {
  fuzz = fuzzPool;
} else {
  const rng = makeRng(SEED);
  const picked = new Set();
  const want = Math.min(10, fuzzPool.length);
  while (picked.size < want) picked.add(Math.floor(rng() * fuzzPool.length));
  fuzz = [...picked].map((i) => fuzzPool[i]);
}
const payloads = [...baseline.strings.map((s) => s.value), ...fuzz];

for (const [label, pair] of pairs) {
  const oracle = encodeOracle[label];
  for (const payload of payloads) {
    const enc = pair.encode.run(payload);
    check('transcode', `${label} encode  input=${reprInput(payload)}`,
      oracle(payload), enc);
    let rt;
    try {
      rt = pair.decode.run(enc);
    } catch (e) {
      fail('transcode', `${label} roundtrip  input=${reprInput(payload)}`,
        payload, `<decode threw: ${e instanceof Error ? e.message : e}>`);
      continue;
    }
    check('transcode', `${label} roundtrip  input=${reprInput(payload)}`, payload, rt);
  }
}

banner('5. Decoder rejects malformed input');
for (const [label, bad] of [
  ['Base64', '@@@@@'],
  ['Base64URL', '@@@@@'],
  ['Hex', 'zzzz'],
  ['Hex', 'abc'],
  ['URL (percent)', '%'],
  ['URL (percent)', '%zz'],
]) {
  const dec = pairs.get(label).decode;
  expectThrow('transcode', `${label} decode rejects ${JSON.stringify(bad)}`, () =>
    dec.run(bad),
  );
}
check(
  'transcode',
  'HTML Entities decode plain+entity text',
  'plain & <b>bold</b> "q" \'a\'',
  pairs
    .get('HTML Entities')
    .decode.run('plain &amp; &lt;b&gt;bold&lt;/b&gt; &quot;q&quot; &#39;a&#39;'),
);
endSection('transcoders');

printSummaryAndExit();
