/**
 * QA CERTIFIER — a single SELF-CONTAINED, source-controlled package
 * (qa-dist/qa.pkg.mjs) that certifies one trusted component file.
 *
 * It is the CONTROL: an independent, audited auditor whose results cannot be
 * externally influenced because it depends on nothing but the Node runtime
 * and the one file it is asked to certify. Baseline, harness, and audited
 * test cases are all inlined here. Its authority comes from PROVENANCE — it
 * is reviewed, promoted, and committed; you fetch the committed package from
 * source control and run THAT against the code to be tested. So when results
 * disagree you know it is the code that is wrong, not the test.
 *
 * Usage: node qa-dist/qa.pkg.mjs <path-to-algorithms.js>
 * (`npm run qa` builds out/algorithms.js and passes it). The extension is
 * built to load that same file, so certified bytes == shipped bytes.
 *
 * Trust chain (no circularity):
 *   1. Provenance — the package is committed when promoted; fetched from
 *                   source control to run (external workflow, not runtime
 *                   self-interrogation — keeps the control dependency-free).
 *   2. KAT        — published vectors are external ground truth.
 *   3. Oracle     — Node `crypto` reproduces the KAT → oracle is trustworthy.
 *   4. Baseline   — generated by that oracle and inlined here; each run
 *                   re-derives it and asserts it is unchanged (tampered data
 *                   / forked OpenSSL → abort).
 *   5. Code       — the supplied algorithms.js computeDigest()/TRANSCODERS
 *                   are asserted equal to the embedded baseline.
 *
 * Every assertion prints to stdout (what, expected, got, diff on mismatch).
 * Non-zero exit on any failure.
 *
 * Env: QA_SEED=<int> transcoder-subset seed; QA_FULL=1 full corpus;
 *      QA_QUIET=1 (or --quiet) collapse PASS lines (FAILs always printed).
 */
import * as crypto from 'crypto';
import { createRequire } from 'module';
import * as fs from 'fs';
import * as path from 'path';
import { KAT } from './vectors.mjs';
import { generateCorpus, makeRng } from './corpus.mjs';

const require = createRequire(import.meta.url);

// ---------------------------------------------------------------------------
// SELF-CONTAINED CONTROL — this package is the auditor.
//
// It depends on NOTHING outside the Node runtime and the one file it is asked
// to certify. It does not read git, the network, env-supplied data, other
// repo files, or even itself: its baseline + harness + audited test cases are
// inlined here. Its authority comes from PROVENANCE, not self-interrogation —
// it is reviewed, promoted, and committed, so you fetch the committed
// qa-dist/qa.pkg.mjs from source control and run THAT. Like an independent
// third-party auditor: trusted because of where it comes from, and its
// results cannot be externally influenced.
// ---------------------------------------------------------------------------

// CODE UNDER TEST — the EXACT trusted component that ships. QA is launched
// with the path to the built algorithms.js as argv[2] and certifies THAT
// file; the extension build loads the same file, so certified == shipped.
const cutArg = process.argv[2];
if (!cutArg) {
  console.error(
    'FATAL  No code-under-test path. Usage: node qa-dist/qa.pkg.mjs ' +
      '<path-to-algorithms.js>  (e.g. `npm run qa` passes out/algorithms.js). ' +
      'QA certifies that exact file; the extension must be built from it.',
  );
  process.exit(1);
}
const cutPath = path.resolve(process.cwd(), cutArg);
let prod;
try {
  prod = require(cutPath);
} catch (e) {
  console.error(`FATAL  cannot load code-under-test ${cutPath}:\n${e}`);
  process.exit(1);
}
const { ALGORITHMS, TRANSCODERS, computeDigest } = prod;
if (!ALGORITHMS || !TRANSCODERS || typeof computeDigest !== 'function') {
  console.error(
    `FATAL  ${cutPath} does not export ALGORITHMS/TRANSCODERS/computeDigest. ` +
      'Is this the built out/algorithms.js?',
  );
  process.exit(1);
}
const cutSha = crypto
  .createHash('sha256')
  .update(fs.readFileSync(cutPath))
  .digest('hex');
// The set of algorithms the CODE UNDER TEST actually exposes.
const codeCryptoSet = new Set(ALGORITHMS.map((a) => a.cryptoName));
console.log(`Certifying code-under-test: ${cutArg}`);
console.log(`  sha256(${path.basename(cutPath)}) = ${cutSha}\n`);

// ---------------------------------------------------------------------------
// The baseline dataset is IMPORTED here and esbuild bundles it INTO this file,
// producing one all-inclusive QA package (qa-dist/qa.pkg.mjs) — JSON data +
// JS test logic as a single committed artifact. `./embedded-data.mjs` is
// generated by `npm run gen:qa` (oracle-computed) and inlined at bundle time;
// it does not exist as a standalone runtime file. qa/run-qa.mjs guarantees
// only the COMMITTED package is ever executed, so this data is, by
// construction, the committed data.
// ---------------------------------------------------------------------------
let DATA;
try {
  DATA = await import('./embedded-data.mjs');
} catch {
  console.error(
    'FATAL  No embedded baseline. This harness runs only from the committed ' +
      'QA package via `npm run qa` (which executes qa-dist/qa.pkg.mjs). To ' +
      'rebuild it: edit sources → `npm run gen:qa` → review/revalidate → ' +
      '`npm run qa:promote` → `git add qa-dist && git commit`.',
  );
  process.exit(1);
}
const baseline = DATA.BASELINE;
const canonicalStrings = DATA.TEST_STRINGS.strings;

const QUIET = process.env.QA_QUIET === '1' || process.argv.includes('--quiet');
const FULL = process.env.QA_FULL === '1';
const SEED = (process.env.QA_SEED && Number(process.env.QA_SEED)) || 0x5eed;

let passCount = 0;
let failCount = 0;
const sectionStats = [];
const failures = []; // collected so the SUMMARY is a complete to-do list

// ---------------------------------------------------------------------------
// Rendering helpers
// ---------------------------------------------------------------------------

function fingerprint(s) {
  return crypto.createHash('sha256').update(s, 'utf8').digest('hex').slice(0, 8);
}
function reprInput(s) {
  if (s.length <= 60) return JSON.stringify(s);
  return (
    `${JSON.stringify(s.slice(0, 24))}…${JSON.stringify(s.slice(-12))}` +
    ` (len=${s.length}, sha256=${fingerprint(s)})`
  );
}
function shortVal(v) {
  v = String(v);
  if (v.length <= 96) return v;
  return `${v.slice(0, 72)}…${v.slice(-12)} (len=${v.length})`;
}
function diff(expected, got) {
  let lenNote;
  if (expected.length !== got.length) {
    lenNote = `lengths differ: expected ${expected.length}, got ${got.length}`;
  }
  const n = Math.min(expected.length, got.length);
  let i = 0;
  for (; i < n; i++) if (expected[i] !== got[i]) break;
  if (i === n && !lenNote) return 'identical (unexpected)';
  const at = i < n ? i : n;
  const parts = [];
  if (lenNote) parts.push(lenNote);
  if (i < n) {
    const eWin = expected.slice(Math.max(0, at - 8), at + 8);
    const gWin = got.slice(Math.max(0, at - 8), at + 8);
    parts.push(
      `first differs at index ${at}: ` +
        `expected ${JSON.stringify(expected[at])} vs got ${JSON.stringify(got[at])}`,
    );
    parts.push(`  expected …${eWin}…`);
    parts.push(`  got      …${gWin}…`);
    parts.push(`           ${' '.repeat(Math.min(8, at) + 1)}^`);
  }
  return parts.join('\n        ');
}
function pass(section, label, expected, got) {
  passCount++;
  if (!QUIET) {
    const tail =
      expected === undefined
        ? ''
        : `  expected=${shortVal(expected)}  got=${shortVal(got)}`;
    console.log(`PASS  ${section}  ${label}${tail}`);
  }
}
function fail(section, label, expected, got, extra) {
  failCount++;
  failures.push(`${section.padEnd(10)} ${label}${extra ? `  — ${extra}` : ''}`);
  console.log(`FAIL  ${section}  ${label}`);
  if (expected !== undefined) {
    console.log(`        expected: ${shortVal(expected)}`);
    console.log(`        got:      ${shortVal(got)}`);
    console.log(`        diff:     ${diff(String(expected), String(got))}`);
  }
  if (extra) console.log(`        note:     ${extra}`);
}
function check(section, label, expected, got, extra) {
  const ok = expected === got;
  if (ok) pass(section, label, expected, got);
  else fail(section, label, expected, got, extra);
  return ok;
}
// Never let a thrown call stop the run: turn a throw into a comparable
// "<threw: …>" value so it is recorded as a normal FAIL and testing
// continues. A full report (all failures) is a complete to-do list.
function safe(thunk) {
  try {
    return { ok: true, value: thunk() };
  } catch (e) {
    return { ok: false, err: e instanceof Error ? e.message : String(e) };
  }
}
function dg(name, val, enc, up) {
  const r = safe(() => computeDigest(name, val, enc, up));
  return r.ok ? r.value : `<threw: ${r.err}>`;
}
function expectThrow(section, label, fn) {
  let threw = false;
  let msg = '';
  try {
    fn();
  } catch (e) {
    threw = true;
    msg = e instanceof Error ? e.message : String(e);
  }
  if (threw) {
    passCount++;
    if (!QUIET) console.log(`PASS  ${section}  ${label}  (rejected: ${msg})`);
  } else {
    failCount++;
    console.log(`FAIL  ${section}  ${label}`);
    console.log('        note:     expected the decode to throw, but it did not');
  }
}
function banner(t) {
  console.log(`\n=== ${t} ===`);
}
function endSection(name) {
  sectionStats.push({ name, pass: passCount, fail: failCount });
}
function printSummaryAndExit() {
  banner('SUMMARY');
  let lp = 0;
  let lf = 0;
  for (const s of sectionStats) {
    console.log(
      `  ${s.name.padEnd(24)}  ${s.pass - lp} passed, ${s.fail - lf} failed`,
    );
    lp = s.pass;
    lf = s.fail;
  }
  console.log(
    `\n  TOTAL: ${passCount} passed, ${failCount} failed ` +
      `(seed=0x${SEED.toString(16)}, ${FULL ? 'FULL' : 'subset'})`,
  );
  if (failCount > 0) {
    console.log(`\n  TO-DO (every failure, full run — nothing skipped):`);
    for (const f of failures) console.log(`    • ${f}`);
    if (unreliable) {
      console.log(
        '\n  NOTE: oracle/baseline integrity failed — some failures above ' +
          'may be downstream consequences; fix the control first.',
      );
    }
    console.log(
      `\nRESULT: FAIL — ${cutArg} is NOT certified. Do not build/ship it.`,
    );
  } else {
    console.log(
      `\nRESULT: PASS — CERTIFIED ${cutArg}\n` +
        `  sha256 = ${cutSha}\n` +
        '  Build the extension from THIS exact file; it is the only trusted ' +
        'hash/transcoder code for the product.',
    );
  }
  process.exit(failCount > 0 ? 1 : 0);
}

// ---------------------------------------------------------------------------
// 1. Validate the oracle against published KAT vectors
// ---------------------------------------------------------------------------

banner('1. Oracle validation (published KAT vectors)');
const availableHashes = new Set(crypto.getHashes());
// `unreliable` is never an early exit — we ALWAYS run every section so the
// full failure list is a complete to-do list. It only annotates the summary
// when the oracle/baseline themselves are suspect (so downstream FAILs may be
// consequences, not independent defects).
let unreliable = false;
for (const v of KAT) {
  const label = `${v.cryptoName}(${JSON.stringify(v.input)})`;
  if (!availableHashes.has(v.cryptoName)) {
    fail('kat', label, v.expected, '<algorithm unavailable in this Node build>');
    unreliable = true;
    continue;
  }
  let oracle;
  try {
    oracle = crypto.createHash(v.cryptoName).update(v.input, 'utf8').digest('hex');
  } catch (e) {
    fail('kat', label, v.expected, `<crypto threw: ${e instanceof Error ? e.message : e}>`);
    unreliable = true;
    continue;
  }
  if (!check('kat', label, v.expected, oracle)) unreliable = true;
}
endSection('oracle/KAT');
if (unreliable) {
  console.log(
    '\nWARNING  The oracle (Node crypto) failed one or more published ' +
      'vectors. Continuing so the full report is produced — but treat all ' +
      'downstream comparisons as suspect until the oracle is fixed.',
  );
}

// ---------------------------------------------------------------------------
// 2. Baseline integrity (frozen dataset is trustworthy in this environment)
// ---------------------------------------------------------------------------

banner('2. Baseline integrity (qa/baseline.json vs oracle + canonical strings)');

// 2a. Frozen strings must match the canonical test-strings.json exactly.
{
  const a = JSON.stringify(canonicalStrings);
  const b = JSON.stringify(baseline.strings);
  if (!check('baseline', 'strings == test-strings.json', a, b,
    'baseline is stale vs canonical strings — regenerate the QA package')) {
    unreliable = true;
  }
}

// (Code-vs-control coverage is its own itemized section below — NOT a single
// abort here, so every gap is enumerated.)

// 2c. Re-derive every baseline digest with the oracle; must be unchanged.
for (const s of baseline.strings) {
  for (const algo of baseline.algorithms) {
    const cell = baseline.hashes[s.id]?.[algo.cryptoName];
    if (!cell) {
      fail('baseline', `${s.id}/${algo.cryptoName} present`, '<hex+base64>', '<missing>');
      unreliable = true;
      continue;
    }
    let raw;
    try {
      raw = crypto.createHash(algo.cryptoName).update(s.value, 'utf8').digest();
    } catch (e) {
      fail('baseline', `${s.id} ${algo.label} (oracle)`, '<hex+base64>',
        `<crypto threw: ${e instanceof Error ? e.message : e}>`,
        'control declares an algorithm this environment cannot hash');
      unreliable = true;
      continue;
    }
    if (!check('baseline', `${s.id} ${algo.label} hex (oracle)`, raw.toString('hex'), cell.hex,
      'baseline hex differs from oracle — tampered or env drift')) unreliable = true;
    if (!check('baseline', `${s.id} ${algo.label} b64 (oracle)`, raw.toString('base64'), cell.base64,
      'baseline base64 differs from oracle — tampered or env drift')) unreliable = true;
  }
}
endSection('baseline integrity');
if (unreliable) {
  console.log(
    '\nWARNING  Oracle and/or baseline integrity failed above. Continuing ' +
      'the full run so nothing is hidden — but some later FAILs may be ' +
      'consequences of this, not independent defects. Fix the control first.',
  );
}

// ---------------------------------------------------------------------------
// 3. Algorithm coverage — gap analysis (code-under-test vs the control)
//    Itemizes, per algorithm:
//      UNTESTED — code exposes it but the control has no certified test
//      MISSING  — control certifies it but the code no longer exposes it
//      BROKEN   — exposed + tested but computeDigest throws/returns nothing
//      covered  — present in both and functionally responding
//    Does NOT abort — every gap is reported; the run still exits non-zero.
// ---------------------------------------------------------------------------

banner('3. Algorithm coverage — untested / missing (code-under-test vs control)');
{
  const controlList = baseline.algorithms; // what the control certifies
  const controlSet = new Set(controlList.map((a) => a.cryptoName));

  for (const a of ALGORITHMS) {
    if (!controlSet.has(a.cryptoName)) {
      fail(
        'coverage',
        `UNTESTED ${a.label} (${a.cryptoName})`,
        '<a certified test in the control>',
        '<none — code-under-test exposes this algorithm but the control has ' +
          'no test/baseline for it>',
        'add it to baseline/algorithms.json, then regenerate + revalidate ' +
          'the QA package',
      );
    }
  }
  for (const a of controlList) {
    if (!codeCryptoSet.has(a.cryptoName)) {
      fail(
        'coverage',
        `MISSING ${a.label} (${a.cryptoName})`,
        '<implemented and listed in the code-under-test>',
        '<absent — the control certifies this algorithm but the ' +
          'code-under-test does not expose it (implementation removed/renamed)>',
      );
      continue;
    }
    // Exposed + tested: confirm the implementation actually responds.
    let digest;
    try {
      digest = computeDigest(a.cryptoName, 'abc', 'hex', false);
    } catch (e) {
      fail(
        'coverage',
        `BROKEN ${a.label} (${a.cryptoName})`,
        '<a hex digest>',
        `<computeDigest threw: ${e instanceof Error ? e.message : e}>`,
        'implementation missing/broken',
      );
      continue;
    }
    if (typeof digest !== 'string' || digest.length === 0) {
      fail(
        'coverage',
        `BROKEN ${a.label} (${a.cryptoName})`,
        '<a non-empty hex digest>',
        JSON.stringify(digest),
        'computeDigest returned no digest — implementation broken',
      );
      continue;
    }
    pass('coverage', `covered ${a.label} (${a.cryptoName})`);
  }
}
endSection('coverage');

// ---------------------------------------------------------------------------
// 4. Certification — code-under-test output vs the FROZEN control baseline
// ---------------------------------------------------------------------------

banner('4. Certification: code-under-test output vs control baseline');
for (const s of baseline.strings) {
  for (const algo of baseline.algorithms) {
    if (!codeCryptoSet.has(algo.cryptoName)) {
      // Already itemized as MISSING in coverage; don't emit a misleading
      // PASS just because computeDigest accepts the name generically.
      continue;
    }
    const cell = baseline.hashes[s.id][algo.cryptoName];
    const inputRepr = `${s.id} (${reprInput(s.value)})`;
    check('hash', `${algo.label} hex   ${inputRepr}`, cell.hex,
      dg(algo.cryptoName, s.value, 'hex', false));
    check('hash', `${algo.label} b64   ${inputRepr}`, cell.base64,
      dg(algo.cryptoName, s.value, 'base64', false));
  }
}

// Encoding-path coverage not stored in the baseline: base64url + uppercase
// hex, checked against the oracle (the same trusted source the baseline used).
const spotAlgos = ['sha256', 'sha3-512', 'blake2b512', 'md5'];
for (const s of baseline.strings.slice(0, 3)) {
  for (const name of spotAlgos) {
    const r = safe(() => crypto.createHash(name).update(s.value, 'utf8').digest());
    if (!r.ok) {
      fail('hash', `${name} spot  ${s.id}`, '<oracle digest>',
        `<oracle threw: ${r.err}>`);
      continue;
    }
    const raw = r.value;
    check('hash', `${name} base64url  ${s.id}`,
      raw.toString('base64url'), dg(name, s.value, 'base64url', false));
    check('hash', `${name} HEX-upper  ${s.id}`,
      raw.toString('hex').toUpperCase(), dg(name, s.value, 'hex', true));
  }
}
endSection('certification');

// ---------------------------------------------------------------------------
// 5. Transcoders / encoders / decoders
// ---------------------------------------------------------------------------

banner(
  `5. Transcoders (${FULL ? 'FULL corpus' : 'random subset'}, seed=0x${SEED.toString(16)})`,
);
const pairs = new Map();
for (const t of TRANSCODERS) {
  const p = pairs.get(t.label) || { label: t.label };
  p[t.direction] = t;
  pairs.set(t.label, p);
}
const encodeOracle = {
  Base64: (s) => Buffer.from(s, 'utf8').toString('base64'),
  Base64URL: (s) => Buffer.from(s, 'utf8').toString('base64url'),
  'URL (percent)': (s) => encodeURIComponent(s),
  Hex: (s) => Buffer.from(s, 'utf8').toString('hex'),
  'HTML Entities': (s) =>
    s.replace(/[&<>"']/g, (c) =>
      ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c])),
};

// Payloads: the frozen baseline strings (always tested) + corpus fuzz +
// real digest hex strings (good payloads).
const corpus = generateCorpus();
const hashPayloads = baseline.strings
  .slice(0, 4)
  .map((s) => baseline.hashes[s.id].sha256.hex);
const fuzzPool = [...corpus.map((c) => c.value), ...hashPayloads];

let fuzz;
if (FULL) {
  fuzz = fuzzPool;
} else {
  const rng = makeRng(SEED);
  const picked = new Set();
  const want = Math.min(10, fuzzPool.length);
  while (picked.size < want) picked.add(Math.floor(rng() * fuzzPool.length));
  fuzz = [...picked].map((i) => fuzzPool[i]);
}
const payloads = [...baseline.strings.map((s) => s.value), ...fuzz];

for (const [label, pair] of pairs) {
  const oracle = encodeOracle[label];
  for (const payload of payloads) {
    const lbl = `input=${reprInput(payload)}`;
    const encR = safe(() => pair.encode.run(payload));
    const oraR = safe(() => oracle(payload));
    check('transcode', `${label} encode  ${lbl}`,
      oraR.ok ? oraR.value : `<oracle threw: ${oraR.err}>`,
      encR.ok ? encR.value : `<encode threw: ${encR.err}>`);
    if (!encR.ok) {
      fail('transcode', `${label} roundtrip  ${lbl}`, payload,
        '<skipped: encode threw>');
      continue;
    }
    const rt = safe(() => pair.decode.run(encR.value));
    check('transcode', `${label} roundtrip  ${lbl}`, payload,
      rt.ok ? rt.value : `<decode threw: ${rt.err}>`);
  }
}

banner('6. Decoder rejects malformed input');
for (const [label, bad] of [
  ['Base64', '@@@@@'],
  ['Base64URL', '@@@@@'],
  ['Hex', 'zzzz'],
  ['Hex', 'abc'],
  ['URL (percent)', '%'],
  ['URL (percent)', '%zz'],
]) {
  const dec = pairs.get(label).decode;
  expectThrow('transcode', `${label} decode rejects ${JSON.stringify(bad)}`, () =>
    dec.run(bad),
  );
}
check(
  'transcode',
  'HTML Entities decode plain+entity text',
  'plain & <b>bold</b> "q" \'a\'',
  pairs
    .get('HTML Entities')
    .decode.run('plain &amp; &lt;b&gt;bold&lt;/b&gt; &quot;q&quot; &#39;a&#39;'),
);
endSection('transcoders');

printSummaryAndExit();
